repository:
  name: clipflow-brand-kit
  description: "🎨 Brand Kit & Visual Identity for the ClipFlow AI Video Automation Platform"
  homepage: "https://github.com/raufA1/clipflow"
  private: false
  has_issues: true
  has_wiki: false
  has_projects: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true

topics:
  - clipflow
  - brand-kit
  - design-system
  - logo
  - banner
  - favicon
  - design
  - ai-tools

labels:
  - name: design
    color: B60205
    description: "Branding, logos, visuals"
  - name: documentation
    color: 0366D6
    description: "Docs, guides, READMEs"