name: Enforce Repository Settings

on:
  push:
    paths:
      - ".github/settings.yml"

jobs:
  repo-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Apply settings
        uses: elstudio/actions-settings@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}